---
repos:
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.21.0  # or higher tag
      hooks:
          - id: yamllint
            args: [--format, parsable]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: debug-statements
          - id: trailing-whitespace
          - id: check-yaml
          - id: check-builtin-literals
          - id: end-of-file-fixer
          - id: check-ast
          - id: check-docstring-first
